// <auto-generated />
namespace TravelTripProje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adskslssks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adskslssks));
        
        string IMigrationMetadata.Id
        {
            get { return "202205032009525_adskslssks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
